import '../models/protocol.dart';

class SourcePageRange {
  final int start;
  final int end;
  const SourcePageRange(this.start, this.end);
}

String protocolKey(Protocol p) => '${'${p.category}'}::${'${p.title}'}';

const Map<String, SourcePageRange> sourcePages = {
  'General::General Guidelines': SourcePageRange(7, 8),
  'General::General Supportive Care': SourcePageRange(9, 10),
  'General::Accident Scene Reports': SourcePageRange(11, 11),
  'General::Functional Needs': SourcePageRange(12, 14),
  'General::Refusal of Care / Patient Consent for Care': SourcePageRange(15, 16),
  'General::Approved Skill Levels': SourcePageRange(17, 19),
  'General::Ambulance Medication Inventory': SourcePageRange(20, 20),
  'General::Medication List': SourcePageRange(21, 21),
  'Medications::Adenocard / Adenosine': SourcePageRange(22, 22),
  'Medications::Albuterol': SourcePageRange(23, 23),
  'Medications::Ammonia Pearls / Inhalants': SourcePageRange(24, 24),
  'Medications::Ancef / Cefazolin': SourcePageRange(25, 25),
  'Medications::Aspirin': SourcePageRange(26, 26),
  'Medications::Atropine': SourcePageRange(27, 27),
  'Medications::Calcium': SourcePageRange(28, 28),
  'Medications::Cardizem / Diltiazem': SourcePageRange(29, 29),
  'Medications::Dextrose': SourcePageRange(30, 30),
  'Medications::Diphenhydramine / Benadryl': SourcePageRange(31, 31),
  'Medications::Dopamine': SourcePageRange(32, 32),
  'Medications::Epinephrine': SourcePageRange(33, 33),
  'Medications::Etomidate / Amidate': SourcePageRange(34, 34),
  'Medications::Fentanyl': SourcePageRange(35, 35),
  'Medications::Glucagon': SourcePageRange(36, 36),
  'Medications::Glutose (Oral Glucose)': SourcePageRange(37, 37),
  'Medications::Ketamine / Ketalar': SourcePageRange(38, 38),
  'Medications::Lasix': SourcePageRange(39, 39),
  'Medications::Lidocaine': SourcePageRange(40, 40),
  'Medications::Lorazepam / Ativan': SourcePageRange(41, 41),
  'Medications::Magnesium Sulfate': SourcePageRange(42, 42),
  'Medications::Midazolam / Versed': SourcePageRange(43, 43),
  'Medications::Morphine Sulfate': SourcePageRange(44, 44),
  'Medications::Naloxone / Narcan': SourcePageRange(45, 45),
  'Medications::Nitroglycerin': SourcePageRange(46, 46),
  'Medications::Oxytocin / Pitocin': SourcePageRange(47, 47),
  'Medications::Phenergan': SourcePageRange(48, 48),
  'Medications::Rocuronium / Zemuron': SourcePageRange(49, 49),
  'Medications::Romazicon / Flumazenil': SourcePageRange(50, 50),
  'Medications::Sodium Bicarb': SourcePageRange(51, 51),
  'Medications::Succinylcholine / Anectine': SourcePageRange(52, 52),
  'Medications::Thiamine': SourcePageRange(53, 53),
  'Medications::Trandate / Labetalol': SourcePageRange(54, 54),
  'Medications::Vecuronium / Norcuron': SourcePageRange(55, 55),
  'Medications::Zofran / Ondansetron': SourcePageRange(56, 56),
  'Procedures::Procedures': SourcePageRange(57, 57),
  'Procedures::Accident Scene Reports': SourcePageRange(58, 58),
  'Procedures::Aerosol Generating Procedures': SourcePageRange(59, 59),
  'Procedures::DNR Procedures': SourcePageRange(60, 61),
  'Procedures::DNR Order Form': SourcePageRange(62, 62),
  'Procedures::EMS Paperwork for ER': SourcePageRange(63, 63),
  'Procedures::Airborne Infectious Disease': SourcePageRange(64, 64),
  'Procedures::Haz-Mat Response Guidelines': SourcePageRange(65, 66),
  'Procedures::Implanted Infusion Port': SourcePageRange(67, 67),
  'Procedures::Infection Control': SourcePageRange(68, 71),
  'Procedures::Intraosseous Infusion': SourcePageRange(72, 73),
  'Procedures::Lab Blood Draws': SourcePageRange(74, 74),
  'Procedures::Mass Casualty Incident': SourcePageRange(75, 75),
  'Procedures::Medical Control Orders': SourcePageRange(76, 77),
  'Procedures::Pandemic Guidelines': SourcePageRange(78, 78),
  'Procedures::Tension Pneumothorax': SourcePageRange(79, 79),
  'Procedures::Trauma Activation Criteria / Mechanism of Injury': SourcePageRange(80, 81),
  'Procedures::Tourniquet': SourcePageRange(82, 82),
  'Cardiac::Cardiac Guidelines': SourcePageRange(83, 83),
  'Cardiac::12 Lead Considerations': SourcePageRange(84, 84),
  'Cardiac::Asystole': SourcePageRange(85, 85),
  'Cardiac::Adult Bradycardia': SourcePageRange(86, 86),
  'Cardiac::Cardiac Guidelines / Chest Pain': SourcePageRange(87, 91),
  'Cardiac::CHF / Unstable Pulmonary Edema': SourcePageRange(92, 92),
  'Cardiac::Adult CPR': SourcePageRange(93, 93),
  'Cardiac::CPR Termination of Resuscitation': SourcePageRange(94, 94),
  'Cardiac::Adult Tachycardia / Cardioversion': SourcePageRange(95, 96),
  'Cardiac::Pulseless Electrical Activity (PEA)': SourcePageRange(97, 97),
  'Cardiac::Transcutaneous Pacing': SourcePageRange(98, 98),
  'Cardiac::Ventricular Fibrillation / Pulseless V-Tach': SourcePageRange(99, 99),
  'Cardiac::Wide Complex V-Tach with Pulse': SourcePageRange(100, 100),
  'Respiratory::Respiratory Guidelines': SourcePageRange(101, 101),
  'Respiratory::Airway Management': SourcePageRange(102, 102),
  'Respiratory::Asthma': SourcePageRange(103, 103),
  'Respiratory::Capnography': SourcePageRange(104, 104),
  'Respiratory::COPD': SourcePageRange(105, 105),
  'Respiratory::CPAP': SourcePageRange(106, 106),
  'Respiratory::Surgical Cricothyrotomy (Bougie Assisted)': SourcePageRange(107, 108),
  'Respiratory::Needle Cricothyrotomy (PTV)': SourcePageRange(109, 110),
  'Respiratory::RSI Guidelines': SourcePageRange(111, 114),
  'Medical::Medical Guidelines': SourcePageRange(115, 115),
  'Medical::Altered Mental Status': SourcePageRange(116, 116),
  'Medical::Allergic Reaction': SourcePageRange(117, 117),
  'Medical::Anaphylaxis': SourcePageRange(118, 118),
  'Medical::Aortic Aneurysm / Dissection': SourcePageRange(119, 119),
  'Medical::Behavioral Health Emergency': SourcePageRange(120, 121),
  'Medical::Carbon Monoxide Poisoning': SourcePageRange(122, 122),
  'Medical::Dehydration': SourcePageRange(123, 123),
  'Medical::Diabetic Emergencies': SourcePageRange(124, 124),
  'Medical::Heat Related Emergencies': SourcePageRange(125, 125),
  'Medical::Hypertension Emergencies': SourcePageRange(126, 128),
  'Medical::Nausea / Vomiting': SourcePageRange(129, 129),
  'Medical::Near Drowning': SourcePageRange(130, 130),
  'Medical::Neurogenic Shock': SourcePageRange(131, 131),
  'Medical::Overdose': SourcePageRange(132, 133),
  'Medical::Pain Management': SourcePageRange(134, 134),
  'Medical::Poisoning': SourcePageRange(135, 135),
  'Medical::Seizures': SourcePageRange(136, 136),
  'Medical::Sepsis Alert Guideline': SourcePageRange(137, 137),
  'Medical::Stroke': SourcePageRange(138, 138),
  'Medical::Weakness / Dizziness': SourcePageRange(139, 139),
  'Trauma::Trauma Guidelines': SourcePageRange(140, 140),
  'Trauma::Burns': SourcePageRange(141, 142),
  'Trauma::Glasgow Coma Scale': SourcePageRange(143, 143),
  'Trauma::Trauma Guidelines (Adult)': SourcePageRange(144, 144),
  'Trauma::Management of Trauma': SourcePageRange(145, 146),
  'Trauma::Mechanism of Injury Criteria': SourcePageRange(147, 148),
  'Trauma::Multi Trauma Incident (MCI)': SourcePageRange(149, 149),
  'Trauma::Orthopedic Injuries': SourcePageRange(150, 150),
  'Trauma::Pelvic Fracture': SourcePageRange(151, 151),
  'Trauma::Prehospital Indications / Decision Scheme': SourcePageRange(152, 153),
  'OB/GYN::OB/GYN Guidelines': SourcePageRange(154, 154),
  'OB/GYN::Labor and Delivery': SourcePageRange(155, 156),
  'OB/GYN::Obstetrical Guidelines': SourcePageRange(155, 155),
  'OB/GYN::Complications During Delivery': SourcePageRange(157, 157),
  'OB/GYN::Postpartum Care of Mother / Infant': SourcePageRange(158, 159),
  'OB/GYN::Neonatal Resuscitation': SourcePageRange(160, 160),
  'OB/GYN::Preeclampsia / Eclampsia': SourcePageRange(161, 161),
  'OB/GYN::Third Trimester Complications': SourcePageRange(162, 162),
  'OB/GYN::Antepartum Hemorrhage': SourcePageRange(163, 163),
  'Pediatric::Pediatric Guidelines': SourcePageRange(164, 164),
  'Pediatric::Pediatric Assessment': SourcePageRange(165, 165),
  'Pediatric::Pediatric Allergic Reaction / Anaphylaxis': SourcePageRange(166, 166),
  'Pediatric::Pediatric Bradycardia': SourcePageRange(167, 167),
  'Pediatric::Pediatric CPR': SourcePageRange(168, 168),
  'Pediatric::Pediatric Asystole / PEA': SourcePageRange(169, 169),
  'Pediatric::Pediatric V-Fib / Pulseless V-Tach': SourcePageRange(170, 170),
  'Pediatric::Pediatric Ventricular Tachycardia': SourcePageRange(171, 171),
  'Pediatric::Pediatric SVT': SourcePageRange(172, 172),
  'Pediatric::Pediatric Breathing Difficulty': SourcePageRange(173, 174),
  'Pediatric::Pediatric Obstructed Airway': SourcePageRange(175, 175),
  'Pediatric::Pediatric Altered Mental Status': SourcePageRange(176, 176),
  'Pediatric::Pediatric Seizures': SourcePageRange(177, 177),
  'Pediatric::Pediatric Overdose / Poisoning': SourcePageRange(178, 178),
  'Pediatric::Pediatric Shock': SourcePageRange(179, 179),
  'Forms::Forms, Signatures, Addenda': SourcePageRange(180, 180),
  'Forms::Certification of Guideline': SourcePageRange(181, 181),
  'Forms::Guideline of Understanding': SourcePageRange(182, 182),
  'Forms::RSI Sign Off Sheet': SourcePageRange(183, 183),
  'Forms::Addenda': SourcePageRange(184, 184),
};
